spring:
  application:
    name: heng-ai-code
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heng_ai_code
    username: root
    password: 115712
  # redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600

  profiles:
    active: local
server:
  port: 9011
  servlet:
    context-path: /api

# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: [ '/**' ]
      packages-to-scan: [ 'com.heng.hengaicode.controller' ]
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true



